### ISSUE TITLE
Graph config serialization

### ISSUE THREAD

**Issue by wiiznokes** [wiiznokes/fan-control#135]
serialize graph like that:
```toml
  [[Graph]]
  name = "Graph"
  input = "max"
  coord = [
      { temp = 50, percent = 30 },
      { temp = 50, percent = 30 },
      { temp = 50, percent = 30 },
  ]
  ```
